AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: NodeLessons lambda functions.

Resources:

  Products:
    Type: AWS::Serverless::Function
    Properties:
      Handler: jobs-stats.handler
      Runtime: nodejs8.10
      Events:
        GetStats:
          Type: Api
          Properties:
            Path: /stats
            Method: get
